name: Erik D Valenta
favicon: null
layout_spectrum: 0.2509
typography_spectrum: 0.56124
title: 'Marketer, Content Creator and Social Media Relations '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f41d1b'
    - '#608e07'
    - '#ebd6c3'
    - '#030200'
    - '#c7a383'
  brandStrength: 0.625
  lightness: 0.125
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
