typography_spectrum: 0.56124
color:
  brandColors:
    - '#f41d1b'
    - '#608e07'
    - '#ebd6c3'
    - '#030200'
    - '#c7a383'
  brandStrength: 0.625
  lightness: 0.125
  saturation: 0.125
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2509
analytics:
  google: null
  facebook: null
  twitter: null
name: Erik D Valenta
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Content Creator, Social Media & Brand Manager'
purpose: []
